### ISSUE TITLE
Exemplo de como baixar xml de notas recebidas

### ISSUE THREAD

**Issue by adrianobalani** [JuniorPolegato/pole#5]
Olá Junior, primeiro quero parabeniza-lo pelo excelente framework feito por você ele tem funções excepcionais e muito bem escrito.

Gostaria de saber se é possivel você me passar algum exemplo de como baixar os xml's das notas fiscais emitidas para um cnpj.

**Comment by JuniorPolegato** [comment]
Olá! Obrigado!

Fazia tempo que não utilizava a funcionalidade de download de NFe, pois o site da NFe é mais permissivo, isto devido ao grande número de restrições e prazo, os quais podem ser vistos na página 23 da Norma Técnica 2012/002:

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=bUBJ/PmtKQo=

Fiz os testes e consertei os erros. Já subi tais correções no GitHub e no PyPI, favor atualizar e então encontrará um arquivo dentro do diretório NFe com nome "teste_download_nfe.py".

Abraços.

**Comment by adrianobalani** [comment]
Olá Junior!
Muito obrigado pela atenção!

Abraços.
